language: node_js
node_js:
  - 12
jdk:
  - oraclejdk8
addon:
  sonarcloud: true
install:
  - "yarn install"
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegopovalz -Dsonar.projectKey=lab22022 -Dsonar.sources='./app' -X
