language: node_js
node_js:
  - 12
jdk:
  - oraclejdk8
addon:
  sonarcloud: true
install:
  - "npm install"
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegopovalz-github -Dsonar.projectKey=lab22022 -Dsonar.branch=main -Dsonar.sources='./app' -X
